export const routes = {
  getAllPublicWallets: '/api/getAllWallets',
  publishPublicWallet: '/api/publishWallet',
  publishProviderWallet: '/api/publishProviderWallet',
  removePublicWalletById: '/api/removeWalletById/:id',
  removePublicWalletByAddress: '/api/removeWalletByAddress/:address',
  removeProviderWalletById: '/api/removeProviderWalletById/:id',
  remoteProviderWalletByAddress: '/api/removeProviderWalletByAddress/:address',
  getPublicWalletById: '/api/getWalletById/:id',
  getProviderWalletById: '/api/getProviderWalletById/:id',
  getProvidedWalletByAddress: '/api/getProvidedWalletByAddress/:address',
  getPublicWalletByAddress: '/api/getWalletByAddress/:address',
  updatePulicWalletById: '/api/updateWalletById/:id',
  updateProviderWalletById: '/api/updateProviderWalletById/:id',
  updatePulicWalletByAddress: '/api/updateWalletByAddress/:address',
  updateProviderWalletByAddress: '/api/updateProviderWalletByAddress/:address',
  getWalletHashByWallet: '/api/getWalletHashByWallet',
  getAllProvidedWallets: '/api/getAllProvidedWallets',
}
